#!/usr/bin/env node
/**
 * Dream Cycle — Nightly Memory Consolidation for Woodhouse
 * Scans recent memory files, extracts themes, writes a dream-cycle summary.
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, basename } from 'node:path';

const MEMORY_DIR = '/Users/FOS_Erik/.openclaw/workspace/memory';
const MESH_DIR = join(MEMORY_DIR, 'mesh');
const LOG_DIR = '/Users/FOS_Erik/.openclaw/logs';

function todayStr() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

function isDateFile(name) {
  return /^\d{4}-\d{2}-\d{2}\.md$/.test(name);
}

async function loadRecent(days = 7) {
  const files = await readdir(MEMORY_DIR);
  const dated = files
    .filter(isDateFile)
    .sort()
    .slice(-days);

  const entries = [];
  for (const f of dated) {
    const content = await readFile(join(MEMORY_DIR, f), 'utf8').catch(() => null);
    if (content) entries.push({ file: f, content });
  }
  return entries;
}

function extractThemes(entries) {
  const themes = new Map();
  const keywords = ['decision', 'lesson', 'project', 'goal', 'idea', 'problem', 'fix', 'plan', 'meeting', 'call', 'email', 'trip', 'health', 'family', 'work', 'code', 'bug', 'deploy', 'infra', 'security'];

  for (const entry of entries) {
    const lines = entry.content.split('\n');
    for (const line of lines) {
      const lower = line.toLowerCase();
      for (const kw of keywords) {
        if (lower.includes(kw)) {
          themes.set(kw, (themes.get(kw) || 0) + 1);
        }
      }
    }
  }

  return [...themes.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
}

async function main() {
  await mkdir(MESH_DIR, { recursive: true });
  await mkdir(LOG_DIR, { recursive: true });

  const entries = await loadRecent(7);

  if (entries.length === 0) {
    console.log(`[${todayStr()}] DREAM_CYCLE_OK — No recent memory files to consolidate.`);
    return;
  }

  const themes = extractThemes(entries);
  const date = todayStr();
  const outfile = join(MESH_DIR, `dream-cycle-${date}.md`);

  const lines = [
    `# Dream Cycle — ${date}`,
    '',
    `**Sources:** ${entries.map(e => e.file).join(', ')}`,
    '',
    '## Themes Detected',
    '',
    ...themes.map(([t, c]) => `- **${t}:** ${c} mentions`),
    '',
    '---',
    '*Auto-generated by Woodhouse dream-cycle.mjs*',
  ];

  await writeFile(outfile, lines.join('\n'), 'utf8');
  console.log(`[${date}] DREAM_CYCLE_OK — Wrote ${outfile} (${entries.length} sources, ${themes.length} themes)`);
}

main().catch(err => {
  console.error(`[${todayStr()}] DREAM_CYCLE_ERROR:`, err.message);
  process.exit(1);
});
