"""
Vigil Tier A - Database Models
SQLite with SQLAlchemy for security logging and metrics.
"""

import os
from datetime import datetime
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Text, Boolean, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session

Base = declarative_base()

# Database setup - use environment variable or default
DATABASE_PATH = os.getenv("DATABASE_PATH", "sqlite:///./vigil_security.db")
engine = create_engine(DATABASE_PATH, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def get_db():
    """Dependency to get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


class PromptLog(Base):
    """Log of all prompts with security analysis results."""
    __tablename__ = "prompt_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    prompt_text = Column(Text)
    blocked = Column(Boolean, default=False)
    reason = Column(Text, nullable=True)
    confidence = Column(Float, default=0.0)
    matched_patterns = Column(JSON, default=list)
    source_ip = Column(String, nullable=True)


class ToolInvocation(Base):
    """Log of tool invocations (MCP, function calls)."""
    __tablename__ = "tool_invocations"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    tool_name = Column(String)
    arguments = Column(JSON)
    blocked = Column(Boolean, default=False)
    block_reason = Column(String, nullable=True)
    result = Column(Text, nullable=True)
    execution_time_ms = Column(Float, nullable=True)


class MemoryAccess(Base):
    """Log of file/memory access operations."""
    __tablename__ = "memory_access"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    access_type = Column(String)  # 'file_read', 'file_write', 'memory_read', etc.
    resource_path = Column(String)
    sensitivity_level = Column(String)  # 'critical', 'high', 'medium', 'low'
    blocked = Column(Boolean, default=False)
    content_hash = Column(String, nullable=True)
    size_bytes = Column(Integer, nullable=True)


class SecurityEvent(Base):
    """Aggregated security events and anomalies."""
    __tablename__ = "security_events"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    event_type = Column(String)  # 'anomaly', 'threshold_breach', 'policy_violation'
    severity = Column(String)  # 'critical', 'high', 'medium', 'low'
    description = Column(Text)
    details = Column(JSON, default=dict)
    acknowledged = Column(Boolean, default=False)


class Device(Base):
    """Network devices detected by Vigil."""
    __tablename__ = "devices"
    
    id = Column(Integer, primary_key=True, index=True)
    mac = Column(String, unique=True, index=True)
    ip = Column(String, index=True)
    hostname = Column(String, nullable=True)
    nickname = Column(String, nullable=True)
    vendor = Column(String, nullable=True)
    device_type = Column(String, nullable=True)
    trust_score = Column(Float, default=50.0)
    containment_status = Column(String, default="observing")
    first_seen = Column(DateTime, default=datetime.utcnow)
    last_seen = Column(DateTime, default=datetime.utcnow)
    online = Column(Boolean, default=True)
    discovery_method = Column(String, default="manual")
    is_known = Column(Boolean, default=False)
    last_ip_change = Column(DateTime, nullable=True)


class Alert(Base):
    """Security alerts generated by Vigil."""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, nullable=True, index=True)
    type = Column(String)  # 'anomaly', 'intrusion', 'policy_violation'
    severity = Column(String)  # 'critical', 'high', 'medium', 'low'
    message = Column(Text)
    acknowledged = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class Event(Base):
    """Activity events for dashboard timeline."""
    __tablename__ = "events"
    
    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, nullable=True, index=True)
    type = Column(String)  # 'device_joined', 'device_left', 'alert_triggered', 'device_blocked'
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)
